### ISSUE TITLE
Missing Titles

### ISSUE THREAD

**Issue by jermnelson** [KnowledgeLinks/Plains2PeaksPilot#22]
5,346 Items are missing required **title** element.

**Comment by ljeremias** [comment]
I know before the holidays I said to forgot these for the initial load.  But I looked at these more and most of these come from American Heritage and History Colorado.  That would mean that much of what they supplied didn't have titles which seems unusual.  I'm going to spend more time on Monday with this.
[MissingTitles.xls.xlsx](https://github.com/KnowledgeLinks/Plains2PeaksPilot/files/1608179/MissingTitles.xls.xlsx)

**Comment by ljeremias** [comment]
I think I figured out the problem with HC's missing titles.  They have two fields "title" and "object Name". 
 They sometimes don't use title but their "Object Name" field can be used to supply a title.  Is it possible to run a change/rule to their data?  When Titles is null choose Object Name?
