### ISSUE TITLE
Missing Dates

### ISSUE THREAD

**Issue by ljeremias** [KnowledgeLinks/Plains2PeaksPilot#27]
_ - @graph - _ - http://purl.org/dc/elements/1.1/date over 35,000 records are blank and for  _ - @graph - _ - http://purl.org/dc/elements/1.1/date - http://purl.org/dc/elements/1.1/date over 57,000 are blank.

**Comment by ljeremias** [comment]
From sample review 2.21.18: no dates for History Colorado, American Heritage and Marmot Libraries.

**Comment by jermnelson** [comment]
Dates now appearing in samples for History Colorado and American Heritage. For Marmot Libraries, missing date in the source JSON data.

**Comment by ahitchner** [comment]
Marmot libraries will start including Date Created in the next harvest - let's not worry about their dates until then.

History Colorado and American Heritage dates now appear.

The only remaining date problem I see is Colorado College - I will update the corresponding ticket.
