### ISSUE TITLE
Use of dcterms:publisher  and edm:dataprovider

### ISSUE THREAD

**Issue by ljeremias** [KnowledgeLinks/Plains2PeaksPilot#3]
I think DPLA expects publisher to be used as publisher of a text, in the traditional sense.  And dataprovider is the contributing institution not the PPC. See page 7 and 9.  At least that is how I am interpreting it.
[MAPv4 (1).pdf](https://github.com/KnowledgeLinks/Plains2PeaksPilot/files/1265138/MAPv4.1.pdf)

**Comment by jermnelson** [comment]
Is fixed as of BIBCAT [commit 4d21d83](https://github.com/KnowledgeLinks/bibcat/commit/4d21d835bdd2331a61af6d7577eba0045bbc993c).
