### ISSUE TITLE
Alternate Title

### ISSUE THREAD

**Issue by ljeremias** [KnowledgeLinks/Plains2PeaksPilot#32]
After review of 2.21.18 sample, It appears as if Alternate title is being mapped to a title field for Colorado College, Univ. of Wyoming, and Co State Pubs.  When it is a true alternate title it should be mapped to its own field.

**Notes from Review**
Alternate Title
125/1000 records are missing titles. Of those, the 15 from American Heritage and Eagle Valley are cataloger error. Remaining “missing” titles (they are actually in a second Title field): 

- Colorado College, 51/304
- CSPL, 47/120
- Univ of Wyo, 12/38

In these records, the main field “_ - @graph - _ - dcterms:title” is blank, but a secondary title field “_ - @graph - _ - dcterms:title - dcterms:title” contains both the title proper and the alternate title. 

- Alternate title should have its own field
- What’s the difference with the two similar title fields named “_ - @graph - _ - dcterms:title” and “_ - @graph - _ - dcterms:title - dcterms:title”

**Comment by jermnelson** [comment]
Titles are now present for most of theses objects. To make sure that we're generating alternative titles correctly, can you add specific objects that from CC, CSPL, or University of Wyoming that have both a main and alternative titles?

**Comment by ahitchner** [comment]
Here is an example of alternate title from each:

CC - https://digitalcc.coloradocollege.edu/islandora/object/coccc%3A8473/view_mods_as_marcxml
CSPL - http://hermes.cde.state.co.us/drupal/islandora/object/co:11539
U of Wyo - https://uwdigital.uwyo.edu/islandora/object/wyu:136217/#page/1/mode/2up
