### ISSUE TITLE
Rights statements for WSL

### ISSUE THREAD

**Issue by ljeremias** [KnowledgeLinks/Plains2PeaksPilot#34]
After review of 2.21.18 sample, Wyoming State Library has no rights statements.  They would like to use, http://rightsstatements.org/vocab/CNE/1.0/

**Comment by jermnelson** [comment]
Running this SPARQL query on the current pilot triplestore:

     PREFIX bf: <http://id.loc.gov/ontologies/bibframe/>
     PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
     PREFIX relators: <http://id.loc.gov/vocabulary/relators/>
     PREFIX schema: <http://schema.org/>

     SELECT (COUNT(?item) as ?count)
     WHERE {
       ?item rdf:type bf:Item ;
           bf:heldBy <http://library.wyo.gov/> .
               FILTER NOT EXISTS {
                   ?item bf:usageAndAccessPolicy ?policy .
           }
    }

Results in 0 items.
