### ISSUE TITLE
Add bf:hasItem to all bf:Instance

### ISSUE THREAD

**Issue by jermnelson** [KnowledgeLinks/Plains2PeaksPilot#38]
To support new Elasticsearch index, all bf:Instance need a bf:hasItem triple linking back to the bf:Item.

**Comment by mstabile75** [comment]
The indexing process looks up from the bf:itemOf property. A bf:hasItem does not need to be added to the triplestore

**Comment by jermnelson** [comment]
I added this issue because the `bf-to-map4.ttl` rules have all changed to require this relationship.  In order to test any fixes for other outstanding issues, the source turtle files need to change to reflect this in the mapping. The `bf-to-map4.ttl` map file needs to work independently of Elasticsearch.
